logging:
  level:
    root: INFO

--- 

spring:
  profiles: production
server:
  port: 8443
  ssl:
    key-store: mykeys.jks
    key-store-password: springboot
    key-password: springboot
    
--- 

spring:
  profiles: test
server:
  port: 8000
logging:
  level:
    root: DEBUG